language: php

dist: bionic

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"

install: travis_retry composer install

script: vendor/bin/phpunit

jobs:
  allow_failures:
    - php: nightly

  include:
    - stage: Metrics and quality
      php: 7.2
      env: CODE_STANDARD
      script:
        - ./vendor/bin/phpcs

    - stage: Metrics and quality
      env: PHPSTAN
      script:
        - ./vendor/bin/phpstan analyse
