sudo: false
language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

matrix:
  allow_failures:
    - php: 7.0
script:
  - ./vendor/bin/phpunit
  - composer require --dev --update-with-dependencies --ignore-platform-reqs --prefer-source vimeo/psalm:dev-master
  - ./vendor/bin/psalm

before_install:
  - travis_retry composer self-update

install:
  - composer install
