sudo: false
language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

script:
  - ./vendor/bin/phpunit

before_install:
  - travis_retry composer self-update

install:
  - composer install

jobs:
  allow_failures:
    - php: 7.4snapshot
    - php: nightly
