language: php

matrix:
  include:
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty
    - php: 5.6
      dist: xenial
    - php: 7.0
      dist: xenial
    - php: 7.1
      dist: bionic
    - php: 7.2
      dist: bionic
    - php: 7.3
      dist: bionic
    - php: 7.4
      dist: bionic
    - php: hhvm-3.24
      dist: trusty

install: travis_retry composer install

script: vendor/bin/phpunit
