name: "Backwards compatibility check"

on:
  pull_request:

jobs:
  bc-check:
    name: "Backwards compatibility check"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
        with:
          fetch-depth: 0

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.1"
          ini-values: memory_limit=-1
          tools: composer:v2, cs2pr, roave/backward-compatibility-check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "BC Check"
        run: |
          composer exec -- roave-backward-compatibility-check --from=${{ github.event.pull_request.base.sha }} --format=github-actions
