name: "Shared Install Dependencies"

on:
  workflow_call:
    inputs:
      dependencies:
        type: "string"
        default: "highest"
        required: true

jobs:
  composer:
    name: "Run Composer"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Install lowest dependencies"
        if: ${{ inputs.dependencies == 'lowest' }}
        run: "composer update --prefer-lowest --no-interaction --no-progress"

      - name: "Install highest dependencies"
        if: ${{ inputs.dependencies == 'highest' }}
        run: "composer update --no-interaction --no-progress"

      - name: "Install locked dependencies"
        if: ${{ inputs.dependencies == 'locked' }}
        run: "composer install --no-interaction --no-progress"

      - name: "Install development dependencies"
        if: ${{ inputs.dependencies == 'development' }}
        run: |
            composer config --no-interaction -- minimum-stability dev
            composer update --no-interaction --no-progress
